@startuml

autonumber

actor "Encargado de Bolsines" as EB

boundary PantallaRegistrarRecepcionBolsin as Pantalla
control GestorRegistrarRecepcionBolsin as Gestor

entity "activa : Sesion" as Sesion
entity Usuario
entity "logueado : Empleado" as Empleado
entity ComisionMedica
entity Bolsin
entity "seleccionado : Bolsin" as BolsinSeleccionado 
entity Remito
entity Documento
entity Estado
entity CambioEstadoBolsin
entity "actual : CambioEstadoBolsin" as CambioEstadoBolsinActual
entity "actual : CambioEstadoDocumentacion" as CambioEstadoDocumentacionActual
entity DetalleRemito
entity TipoDocumento

' ==========================================
' Inicio CU
' ==========================================

create Pantalla

EB ->> Pantalla : seleccionarRegistrarRecepcionDeBolsin()

Pantalla --> Pantalla : habilitarPantalla()

create Gestor

Pantalla --> Gestor : RegistrarRecepcionDeBolsin()

activate Gestor

' ==========================================
' Obtener CM del usuario
' ==========================================
Gestor -> Gestor : buscarCM()
Gestor -> Gestor : obtenerUsuario()

Gestor -> Sesion : obtenerUsuario()

Sesion -> Usuario : obtenerEmpleado()

Gestor -> Empleado : getCM()

Gestor -> Pantalla : mostrarCM()

' ==========================================
' Buscar bolsines enviados
' ==========================================

Gestor -> Gestor : buscarEnviados(cmUsuario)


loop por cada bolsin
    Gestor -> Bolsin : obtenerCMDestino()
    
    loop por cada bolsin con CM == CMDestino
        Gestor -> Bolsin : sosEnviado()
        Bolsin -> CambioEstadoBolsin : sosActual()
        CambioEstadoBolsin -> Estado : esAmbitoBolsin()
        CambioEstadoBolsin -> Estado : esEnviado()
        Gestor -> Bolsin : getNroPrecinto()
        
        Gestor -> Gestor : obtenerCMOrigen()

        loop por cada Comision Medica
            Gestor -> ComisionMedica : getNombre()
            Gestor -> Bolsin : esTuCMOrigen()
            
        end
    end
end


Gestor -> Pantalla : mostrarBolsines(listaBolsines)

' ==========================================
' Selección de bolsín
' ==========================================

Gestor -> Pantalla : seleccionarBolsin()
EB -> Pantalla : tomarSeleccion()

Pantalla -> Gestor : tomarSeleccion(bolsin)

Gestor -> Gestor : obtenerRemitos()

loop por cada remito
    Gestor -> BolsinSeleccionado : obtenerInformacionRemito()
    BolsinSeleccionado -> Remito : obtenerNroRemito()
    BolsinSeleccionado -> Remito : buscarDocumentacion()
    

    loop por cada documento
        Remito -> DetalleRemito : getDocumentacion()
        DetalleRemito -> Documento : getAsunto()
        Documento -> TipoDocumento : getNombre()
    end
end

Gestor -> Pantalla : mostrarNroRemito()
Gestor -> Pantalla : mostrarAsunto()
Gestor -> Pantalla : mostrarTipoDocumentacion()

' ==========================================
' Selección opción recepción
' ==========================================

Gestor -> Pantalla : mostrarOpcionesRecepcion()

EB -> Pantalla : tomarOpcionRecepcion()

Pantalla -> Gestor : tomarOpcionRecepcion()

Gestor --> Pantalla : solicitarConfirmacion()

EB -> Pantalla : tomarConfirmacion()

Pantalla -> Gestor : confirmarOperacion()

' ==========================================
' Actualización de estados
' ==========================================

Gestor -> Gestor : actualizarEstados()
Gestor -> Gestor : obtenerFechaYHoraActual()
Gestor -> Sesion : obtenerUsuario()
Sesion -> Usuario : obtenerEmpleado()
loop por cada Estado
    Gestor -> Estado : esAmbitoBolsin()
    Gestor -> Estado : esRecibidoEnCMDestino()

end
loop por cada Estado
    Gestor -> Estado : esAmbitoRemito()
    Gestor -> Estado : esRecibidoYAceptado()

end
loop por cada Estado
    Gestor -> Estado : esAmbitoDocumentacion()
    Gestor -> Estado : esRecibidaYAceptada()

end

Gestor -> BolsinSeleccionado : actualizarEstadoBolsin()
BolsinSeleccionado -> CambioEstadoBolsinActual : setFechaYHoraFin()

BolsinSeleccionado -> BolsinSeleccionado : crearCEBolsin()
create CambioEstadoBolsin
BolsinSeleccionado --> CambioEstadoBolsin : new()


loop por cada remito
    BolsinSeleccionado -> Remito : setEstado(Recibido y Aceptado)
    Remito -> DetalleRemito : actualizarEstadoDoc()

    loop por cada documento
        DetalleRemito -> Documento : setEstado(Recibida y Aceptada)
        Documento -> CambioEstadoDocumentacionActual : setFechaHoraFin()
        
        create CambioEstadoDocumentacion
        Documento --> CambioEstadoDocumentacion : new()

    end
end


' ==========================================
' Notificación
' ==========================================

Gestor -> ComisionMedica : notificarRecepcion()

Gestor --> Pantalla : informarExito()

deactivate Gestor

@enduml