@startuml

autonumber

actor "Encargado de Bolsines" as EB

boundary PantallaRegistrarRecepcionBolsin as Pantalla
control GestorRegistrarRecepcionBolsin as Gestor

entity "activa : Sesion" as Sesion
entity Usuario
entity "logueado : Empleado" as Empleado
entity ComisionMedica
entity Bolsin
entity Remito
entity Documento
entity Estado
entity CambioEstadoBolsin
entity CambioEstadoDocumentacion
entity DetalleRemito
entity TipoDocumento

' ==========================================
' Inicio CU
' ==========================================

create Pantalla

EB ->> Pantalla : seleccionarRegistrarRecepcionDeBolsin()

Pantalla --> Pantalla : habilitarPantalla()

create Gestor

Pantalla ->> Gestor : RegistrarRecepcionDeBolsin()

activate Gestor

' ==========================================
' Obtener CM del usuario
' ==========================================
Gestor -> Gestor : buscarCM()
Gestor -> Gestor : obtenerUsuario()

Gestor -> Sesion : obtenerUsuario()

Sesion -> Usuario : obtenerEmpleado()

Gestor -> Empleado : getCM()

' ==========================================
' Buscar bolsines enviados
' ==========================================

Gestor -> Bolsin : buscarEnviados(cmUsuario)
Bolsin --> Gestor : listaBolsines

Gestor --> Pantalla : mostrarBolsines(listaBolsines)

' ==========================================
' Selección de bolsín
' ==========================================

EB -> Pantalla : seleccionarBolsin()

Pantalla -> Gestor : tomarSeleccion(bolsin)

Gestor -> Bolsin : obtenerInformacionRemito()
Bolsin --> Gestor : remitos

loop por cada remito
    Gestor -> Remito : obtenerDetalle()
    Remito --> Gestor : detalle

    loop por cada documento
        Gestor -> Documento : getDatosDocumentacion()
        Documento --> Gestor : datosDoc
    end
end

Gestor --> Pantalla : mostrarDetalle()

' ==========================================
' Selección opción recepción
' ==========================================

Pantalla --> EB : solicitarOpcionRecepcion()

EB -> Pantalla : opcionRecepcion()

Pantalla -> Gestor : registrarRecepcion(opcion)

Gestor --> Pantalla : solicitarConfirmacion()

EB -> Pantalla : confirmar()

Pantalla -> Gestor : confirmarOperacion()

' ==========================================
' Actualización de estados
' ==========================================

loop por cada remito
    Gestor -> Remito : setEstado(Recibido y Aceptado)

    loop por cada documento
        Gestor -> Documento : setEstado(Recibida y Aceptada)
    end
end

Gestor -> Bolsin : crearCEBolsin()
Gestor -> Bolsin : setEstado(Recibido en CM destino)

' ==========================================
' Notificación
' ==========================================

Gestor -> ComisionMedica : notificarRecepcion()

Gestor --> Pantalla : informarExito()

deactivate Gestor

@enduml